server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drones
    username: ${psql.username}
    password: ${psql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  config:
    import:
      - classpath:hidden.yml
      - classpath:examples.yml

drones:
  medication:
    images:
      path: images

management:
  endpoints:
    web:
      exposure:
        include: auditevents
