server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drones-test
    username: ${psql.username}
    password: ${psql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
  liquibase:
    enabled: false
  config:
    import: classpath:hidden.yml

drones:
  medication:
    images:
      path: images

management:
  endpoints:
    web:
      exposure:
        include: auditevents
